### ISSUE TITLE
Deprecation warnings from _classes.scss

### ISSUE THREAD

**Issue by tstermitz** [zurb/motion-ui#106] opened 2018-04-28 22:43 UTC
DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("shake")) instead.

This is easy to fix in the mixin "motion-ui-animations" after line 75 in V1.2.3

@mixin motion-ui-animations {"
  .shake    { @include mui-animation(get-function("shake")); }
  .spin-cw  { @include mui-animation(get-function("spin")); }
  .spin-ccw { @include mui-animation(spin(ccw)); }
  .wiggle   { @include mui-animation(get-function("wiggle")); }

I'm not sure why mui-animation(spin(ccs)) did not throw a warning.

Here are my node_modules dependencies:
  "devDependencies": {
    "browser-sync": "^2.23.6",
    "del": "^2.2.0",
    "extend": "^3.0.0",
    "foundation-sites": "~6.3.1",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^4.0.0",
    "gulp-cached": "^1.1.0",
    "gulp-load-plugins": "^1.5.0",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^3.1.0",
    "gulp-sass-lint": "^1.3.4",
    "gulp-shell": "^0.5.2",
    "gulp-size": "^3.0.0",
    "gulp-sourcemaps": "^2.6.4",
    "motion-ui": "~1.2.3",
    "node-sass-import-once": "^1.2.0",
    "rimraf": "*"
  },

**Comment by ncoden** [comment] 2018-04-28 22:54
Duplicate of https://github.com/zurb/motion-ui/issues/99. Resolved in https://github.com/zurb/motion-ui/pull/100

**Closed by ncoden** 2018-04-28 22:54 UTC
