### ISSUE TITLE
DEPRECATION WARNING: Passing a string to call()

### ISSUE THREAD

**Issue by raphaelsanchez** [zurb/motion-ui#104] opened 2018-04-18 17:13 UTC
I found an issue `DEPRECATION WARNING: Passing a string to call()`

I found how to fix this. How can I submit my modification ?

**Comment by ncoden** [comment] 2018-04-19 18:57
Duplicate of https://github.com/zurb/motion-ui/issues/99. Resolved in https://github.com/zurb/motion-ui/pull/100

**Closed by ncoden** 2018-04-19 18:57 UTC
Labels: duplicate
